---
- name: Install Docker and dependencies
  hosts: monitoring,kubeserver
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install ca-certificates and curl
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        mode: '0755'
        state: directory

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Install Docker and related packages
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        
    - name: Install Docker Buildx plugin
      shell: docker buildx install
      args:
        executable: /bin/bash

    - name: Install Docker Compose plugin
      shell: curl -sSL https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh