---
- name: Install MicroK8s
  hosts: kubeserver
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install snapd package
      apt:
        name: snapd
        state: present

    - name: Install MicroK8s
      command: snap install microk8s --classic

